# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: ticket_db
  pool: 5
  username: govind
  password: gp
test:
  adapter: mysql2
  encoding: utf8
  database: ticket_db
  pool: 5
  username: govind
  password: gp
production:
  adapter: mysql2
  encoding: utf8
  database: ticket_db
  pool: 5
  username: govind
  password: gp
